config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#index'
  devise_for :users, only: %i[sessions registrations]
  resources :plans, only: %i[index show]

  devise_for :administrators, only: %i[sessions], controllers: { sessions: 'admins/sessions' }
  namespace :admins do
    root to: 'plans#index'
    resources :plans, only: %i[index edit update]
    resources :ingredient_sets, only: %i[index new create edit update]
    resources :deliveries, only: %i[index]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  extend Enumerize

  belongs_to :user

  enumerize :status, in: %w[preparing delivered stopped]
  enumerize :time_slot, in: %i[am pm]

  scope :default_order, -> { order(id: :desc) }
end

app/models/ingredient_set.rb
class IngredientSet < ApplicationRecord
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :weight, numericality: { greater_than_or_equal_to: 0, allow_blank: true }

  scope :default_order, -> { order(:id) }
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plan_items, dependent: :restrict_with_exception
  has_many :ingredient_sets, through: :plan_items

  validates :name, presence: true

  scope :default_order, -> { order(:id) }
end

app/models/plan_item.rb
class PlanItem < ApplicationRecord
  belongs_to :plan
  belongs_to :ingredient_set
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, authentication_keys: %i[login_key]

  belongs_to :plan, optional: true
  has_many :deliveries, dependent: :restrict_with_exception

  enumerize :delivery_cycle, in: %w[weekly bi_monthly]

  validates :login_key, uniqueness: true
  validates :name, presence: true

  after_update :create_delivery!, if: :delivery_creatable?

  def email_required?
    false
  end

  private

  def delivery_creatable?
    return false if [ address, delivery_cycle, plan_id ].any?(&:blank?)
    return true if !deliveries.exists?

    !deliveries.with_status(:preparing).exists?
  end

  def create_delivery!
    scheduled_on =
      case delivery_cycle
      when 'weekly'
        1.week.since
      when 'bi_monthly'
        2.weeks.since
      else
        raise ArgumentError, "Invalid delivery_cycle: #{delivery_cycle}"
      end
    deliveries.create!(scheduled_on:, time_slot: 'am')
  end
end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_administrator!

  layout 'admins/application'
end

app/controllers/admins/deliveries_controller.rb
class Admins::DeliveriesController < Admins::ApplicationController
  def index
    @deliveries = Delivery.default_order
  end
end

app/controllers/admins/ingredient_sets_controller.rb
class Admins::IngredientSetsController < Admins::ApplicationController
  before_action :set_ingredient_set, only: %i[edit update]

  def index
    @ingredient_sets = IngredientSet.default_order
  end

  def new
    @ingredient_set = IngredientSet.new
  end
  
  def create
    @ingredient_set = IngredientSet.new(ingredient_set_params)
    if @ingredient_set.save
      redirect_to admins_ingredient_sets_url, notice: '食材セットを作成しました。', status: :see_other
    else
      render :new, status: :unprocessable_content
    end
  end

  def edit
  end
  
  def update
    if @ingredient_set.update(ingredient_set_params)
      redirect_to edit_admins_ingredient_set_url(@ingredient_set), notice: '食材セットを更新しました。'
    else
      render :edit, status: :unprocessable_content
    end
  end
  
  private
  
  def set_ingredient_set
    @ingredient_set = IngredientSet.find(params[:id])
  end
  
  def ingredient_set_params
    params.expect(ingredient_set: %i[name price content weight refrigerated allergy_info])
  end
end

app/controllers/admins/plans_controller.rb
class Admins::PlansController < Admins::ApplicationController
  before_action :set_plan, only: %i[edit update]
  before_action :set_ingredient_sets, only: %i[edit update]

  def index
    @plans = Plan.default_order
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to admins_plans_path, notice: 'プランを更新しました。', status: :see_other
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def set_ingredient_sets
    @ingredient_sets = IngredientSet.default_order
  end

  def plan_params
    params.expect(plan: [ :name, :description, ingredient_set_ids: [] ])
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource)
    new_administrator_session_path
  end

  def after_sign_in_path_for(_resource)
    admins_root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  allow_browser versions: :modern

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[login_key name])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[login_key])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email address telephone_number allergy_note delivery_cycle plan_id
                                               password password_confirmation current_password])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[show]

  def index
    @plans = Plan.default_order
  end

  def show
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/deliveries/_delivery.html.haml
.card
  .card-body
    %p ユーザー名: #{delivery.user.name}
    %p 住所: #{delivery.user.address}
    %p 配達日: #{l(delivery.scheduled_on)}
    %p プラン: #{delivery.user.plan.name}
    %p ステータス: #{delivery.status.text}

app/views/admins/deliveries/index.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 配達一覧
    .vstack
      - @deliveries.each do |delivery|
        = render 'delivery', delivery:

app/views/admins/ingredient_sets/_form.html.haml
= simple_form_for ingredient_set, url: admins_ingredient_sets_path do |f|
  = f.error_notification
  = f.input :name
  = f.input :content
  = f.input :price
  = f.input :weight
  = f.input :refrigerated
  = f.input :allergy_info
  = f.submit class: 'btn btn-primary'

app/views/admins/ingredient_sets/edit.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 食事セット編集
    .mb-3
      = render 'form', ingredient_set: @ingredient_set

app/views/admins/ingredient_sets/index.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 食材セット一覧
    .mb-3= link_to '新規作成', new_admins_ingredient_set_path, class: 'btn btn-primary'
    %ul.list-group
      - @ingredient_sets.each do |ingredient_set|
        %li.list-group-item
          = link_to edit_admins_ingredient_set_path(ingredient_set) do
            %p.mb-0= ingredient_set.name

app/views/admins/ingredient_sets/new.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 食事セット作成
    .mb-3
      = render 'form', ingredient_set: @ingredient_set

app/views/admins/plans/edit.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 プラン編集
    .mb-3
      = simple_form_for @plan, url: admins_plan_path(@plan) do |f|
        = f.input :name
        = f.input :description
        = f.association :ingredient_sets, collection: @ingredient_sets
        = f.button :submit, '更新', class: 'btn btn-primary'

app/views/admins/plans/index.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 プラン一覧
    .card-group.justify-content-around
      - @plans.each do |plan|
        = link_to edit_admins_plan_path(plan), class: 'text-decoration-none' do
          = render 'plan', plan:

app/views/layouts/_flash.html.haml
.toast-container.position-fixed.top-0.end-0.pt-5.pe-2
  - flash.each do |key, value|
    .toast{ data: { controller: :toast }, role: :alert }
      .toast-body{ class: "d-flex justify-content-between align-items-center text-white bg-#{key == "notice" ? "success" : "danger"}" }
        %p.mb-0= value
        %button.btn-close{ type: :button, data: { bs: { dismiss: :toast } }, aria: { label: "閉じる" } }

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.shadow.sticky-top.bg-white
  .container-fluid
    = link_to '食材デリバリー', root_path, class: 'navbar-brand'
    %button.navbar-toggler{ type: :button, data: { bs: { toggle: :collapse, target: '#navbar-nav' } }, aria: { controls: 'navbar-nav', expanded: false } }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-nav
      %ul.navbar-nav
        %li.nav-item
          = link_to 'プラン一覧', plans_path, class: 'nav-link'
        %li.nav-item
          = link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link'
        %li.nav-item
          = button_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo_confirm: 'ログアウトしますか？' }, class: 'nav-link'

app/views/layouts/_rails-template-inspector.html.haml
%script{ src: "https://cdn.skypack.dev/@aki77/rails-template-inspector@^0.5.0", type: "module" }
%rails-inspector{ "combo-key": "command-shift-v", root: "#{Rails.root}", "url-prefix": "x-mine://open?file=" }

app/views/layouts/admins/_nav.html.haml
%nav.navbar.navbar-expand-lg.shadow.sticky-top.bg-white
  .container-fluid
    = link_to '食材デリバリー', admins_root_path, class: 'navbar-brand'
    %button.navbar-toggler{ type: :button, data: { bs: { toggle: :collapse, target: '#navbar-nav' } }, aria: { controls: 'navbar-nav', expanded: false } }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-nav
      %ul.navbar-nav
        %li.nav-item
          = link_to 'プラン一覧', admins_plans_path, class: 'nav-link'
        %li.nav-item
          = link_to '食材セット一覧', admins_ingredient_sets_path, class: 'nav-link'
        %li.nav-item
          = link_to '配達一覧', admins_deliveries_path, class: 'nav-link'
        %li.nav-item
          = button_to 'ログアウト', destroy_administrator_session_path, method: :delete, data: { turbo_confirm: 'ログアウトしますか？' }, class: 'nav-link'

app/views/layouts/admins/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }
    %title= content_for(:title) || "食材デリバリー"
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }
    %meta{ content: "yes", name: "apple-mobile-web-app-capable" }
    %meta{ content: "yes", name: "mobile-web-app-capable" }
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: "/icon.png", rel: "icon", type: "image/png" }
    %link{ href: "/icon.svg", rel: "icon", type: "image/svg+xml" }
    %link{ href: "/icon.png", rel: "apple-touch-icon" }
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    - if administrator_signed_in?
      = render "layouts/admins/nav"
    = render "layouts/flash"
    = yield
    - if Rails.env.local?
      = render "layouts/rails-template-inspector"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }
    %title= content_for(:title) || "食材デリバリー"
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }
    %meta{ content: "yes", name: "apple-mobile-web-app-capable" }
    %meta{ content: "yes", name: "mobile-web-app-capable" }
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: "/icon.png", rel: "icon", type: "image/png" }
    %link{ href: "/icon.svg", rel: "icon", type: "image/svg+xml" }
    %link{ href: "/icon.png", rel: "apple-touch-icon" }
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    - if user_signed_in?
      = render "layouts/nav"
    = render "layouts/flash"
    = yield
    - if Rails.env.local?
      = render "layouts/rails-template-inspector"

app/views/plans/_ingredient_set.html.haml
.card
  .card-body
    %h5.card-title= ingredient_set.name
    %hr
    .card-text
      = simple_format(h(ingredient_set.content))
      %ul.list-group.list-group-flush
        %li.list-group-item #{IngredientSet.human_attribute_name(:price)}: #{number_to_currency(ingredient_set.price)}
        %li.list-group-item #{IngredientSet.human_attribute_name(:weight)}: #{ingredient_set.weight}
        - if ingredient_set.refrigerated?
          %li.list-group-item 冷蔵品
        %li.list-group-item #{IngredientSet.human_attribute_name(:allergy_info)}: #{simple_format(h(ingredient_set.allergy_info))}

app/views/plans/_plan.html.haml
.card
  .card-body
    %h5.card-title= plan.name
    .card-text
      = simple_format(h(plan.description))

app/views/plans/index.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 プラン一覧
    .card-group.justify-content-around
      - @plans.each do |plan|
        = link_to plan_path(plan), class: 'text-decoration-none' do
          = render 'plan', plan:

app/views/plans/show.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 #{@plan.name}プラン
    %p.mb-3= @plan.description
    %legend.fs-4= Plan.human_attribute_name(:ingredient_sets)
    .row.row-cols-1.g-4
      - @plan.ingredient_sets.default_order.each do |ingredient_set|
        .col= render 'ingredient_set', ingredient_set: